Update `membrane_core` to 0.10.0. Fix tests
membraneframework/membrane_rtp_vp8_plugin pull request #12
Opened 2022-05-05 14:47 UTC by mickel8

2022-05-09 21:26 UTC, mickel8 commented
I pasted in the description, difference between old reference file used in `"depayloading rtp with vp8" ` test (on the left in the diff) and current output of this test (on the right in the diff). When running `ffplay test/results/result.ivf` everything looks fine. I suppose that those small changes in timestamps are related to getting rid of `Ratio.t()` in some other repositories but I am not 100% sure.

2022-05-10 10:03 UTC, varsill requested changes

2022-05-10 10:22 UTC, mickel8 commented on mix.exs
> +       github: "membraneframework/membrane_rtp_plugin", branch: "fix-ssrcrouter-eos", only: :test},
Yeap, exactly, I am waiting for RTP plugin

2022-05-10 10:22 UTC, mickel8 commented on test/test_helper.exs
> +ExUnit.start(capture_log: true)
Thanks to this we will see debug logs only when some test fails. I think we started addding this in other repos too

2022-05-11 06:53 UTC, varsill commented on test/test_helper.exs
> +ExUnit.start(capture_log: true)
Oh, that's a good idea.

2022-05-12 11:56 UTC, mat-hek approved these changes

2022-05-16 11:47 UTC, merged