Depayloader
membraneframework/membrane_rtp_vp8_plugin pull request #2
Opened 2021-02-10 13:30 UTC by AndrzejPodo

Following PR introduces three important modules:
* `Membrane.RTP.VP8.Depayloader`- responsible for implementing `Membrane.Filter` callbacks. This module utilises `Membrane.RTP.VP8.Frame` module for frame reconstruction.
* `Membrane.RTP.VP8.Frame` - provides `Frame` struct that acts as accumulator and multiple functions used for reconstructing VP8 frame.
* `Membrane.RTP.VP8.PayloadDescriptor` - provides `PayloadDescriptor` structure and functions for dealing with that structure - as for now parsing it.

2021-02-19 09:32 UTC, mat-hek requested changes

2021-02-19 09:32 UTC, mat-hek commented on .gitignore
> +results/
```suggestion
/test/results/
```

2021-02-19 09:32 UTC, mat-hek commented on lib/depayloader.ex
> +      ) do
```suggestion
  def handle_process(:input, buffer, _ctx, state) do
```

2021-02-19 09:32 UTC, mat-hek commented on lib/depayloader.ex
> +          [buffer: {:output, %{buffer | payload: frame, metadata: state.last_buffer_metadata}}]},
Why is metadata shifted by one buffer? It should be rather the metadata from the first buffer in of the frame

2021-02-19 09:32 UTC, mat-hek commented on lib/frame.ex
> +  defguardp equal_timestamp(last_timestamp, next_timestamp) when last_timestamp == next_timestamp
I think this is a bit overkill

2021-02-19 09:32 UTC, mat-hek commented on lib/frame.ex
> +          | {:incomplete, t()}
I'd return `{:ok, :incomplete, t()}`

2021-03-01 14:16 UTC, AndrzejPodo commented on lib/frame.ex
> +  defguardp equal_timestamp(last_timestamp, next_timestamp) when last_timestamp == next_timestamp
You mean the `equal_timestamp` guard?

2021-03-01 14:34 UTC, AndrzejPodo commented on lib/depayloader.ex
> +          [buffer: {:output, %{buffer | payload: frame, metadata: state.last_buffer_metadata}}]},
It is not shifted, metadata is taken from the last buffer that makes up the frame, but of course it can be taken from the first buffer. The only difference will be in rtp `sequence_number` and `marker` field.

2021-03-02 11:40 UTC, mat-hek requested changes

2021-03-02 11:40 UTC, mat-hek commented on .gitignore
> +rfc_bool_encoding/
It should rather be not added to git, not ignored

2021-03-02 11:40 UTC, mat-hek commented on lib/depayloader.ex
> +         %State{state | frame_acc: acc, first_buffer_metadata: buffer.metadata}}
shouldn't `first_buffer_metadata` be set to `nil` here?

2021-03-05 11:07 UTC, AndrzejPodo commented on lib/depayloader.ex
> +         %State{state | frame_acc: acc, first_buffer_metadata: buffer.metadata}}
I don't thinks so. In payload descriptors in VP8 we have only information that the buffer is first buffer of the frame, so complete frame is released when we encounter first buffer of next frame. After emitting full frame, acc contains first fragment of next frame and first_buffer_metadata is updated.

2021-03-08 10:01 UTC, mat-hek commented on lib/frame.ex
> +  defguardp equal_timestamp(last_timestamp, next_timestamp) when last_timestamp == next_timestamp
Yes. BTW, the name `is_next` in the guard above is quite cryptic

2021-03-17 13:35 UTC, mat-hek approved these changes

2021-03-17 14:32 UTC, merged