Payloader
membraneframework/membrane_rtp_vp8_plugin pull request #3
Opened 2021-02-12 16:10 UTC by AndrzejPodo

Payloader as for now realises the easier to implement packetization method that doesn't require retrieval of VP8 partition boundaries from payload header. Packetization methods are described here: [link](https://tools.ietf.org/html/rfc7741#section-4.4)

>It is OPTIONAL for a packetizer implementing
   this RTP specification to pay attention to the partition boundaries
   within an encoded frame.  If packetization of a frame is done without
   considering the partition boundaries, the PID field MAY be set to 0
   for all packets and the S bit MUST NOT be set to 1 for any other
   packet than the first.

2021-02-19 09:39 UTC, mat-hek requested changes

2021-02-19 09:39 UTC, mat-hek commented on lib/payload_descriptor.ex
> +      }) do
let's do the match in the function body

2021-02-19 09:39 UTC, mat-hek commented on lib/payloader.ex
> +    max_chunk_size = ceil(byte_size(payload) / chunk_count)
isn't max_chunk_size equal to max_payload_size?

2021-03-01 15:49 UTC, AndrzejPodo commented on lib/payloader.ex
> +    max_chunk_size = ceil(byte_size(payload) / chunk_count)
No, I've observed that for example Chrome when payloading tries to spread payload over packets equally, so for example when max payload is 1400, and frame of size 1500 is to be payloaded, than two packets with payload 750 are produced instead of one with payload 1400 and second with payload 100.

2021-03-02 11:45 UTC, mat-hek commented on lib/payloader.ex
> +    max_chunk_size = ceil(byte_size(payload) / chunk_count)
But that's not what you implemented here, you're basically assigning max_payload_size to max_chunk_size (maybe +- 1 because of ceiling)

2021-03-02 11:55 UTC, mat-hek approved these changes

2021-03-02 11:55 UTC, mat-hek commented on .gitignore
> +rfc_bool_encoding/
to remove

2021-03-05 11:13 UTC, merged