Advanced payloader
membraneframework/membrane_rtp_vp8_plugin pull request #4
Opened 2021-03-02 09:54 UTC by AndrzejPodo

Payloader that cares about partition boundaries.
This PR contains:
*  some new payloader logic to handle new type of payloading,
*  `frame_header.ex` - a module responsible for parsing frame header,
*  `boolean_decoder.ex`- a module that implements boolean decoder necessary for decoding compressed part of frame
*  bunch of test (`bool_decoder_test.exs`, `frame_header_test.exs`, new cases in `payloader_test.exs`)
*  `capture_buffer_test.exs` - script used to dump buffers with frames to the file as erlang binaries

2021-04-01 12:46 UTC, mat-hek requested changes

2021-04-08 09:03 UTC, AndrzejPodo commented on lib/boolean_decoder.ex
> +      Enum.reduce_while(1..@max_int_32, state, fn _i, state ->
It's was just a dirty imitation of while loop :P If you look closer, each iteration is multiplying range by 2, and when range is `>= 128` loop halts, so actually the number of iterations is restricted by `log2(128) = 7`. I'll change range to 7 and it should work exactly the same.

2021-04-08 09:11 UTC, AndrzejPodo commented on lib/boolean_decoder.ex
> +defmodule Membrane.RTP.VP8.BooleanDecoder do
The name doesn't come from decoding booleans, but from type of coding, it is `boolean entropy coding`. So I'll change this to `BooleanEntropyDecoder`.

2021-04-08 12:57 UTC, AndrzejPodo commented on lib/boolean_decoder.ex
> +    split2 = split * 256
I'm not sure what would be more meaningful, this is exactly the same value but shifted by 8 bits in order to compare it with `value`. It is necessary because `value` is stored in 16bit and we actually operate here on values from range `0..1`, so `value` is like `0.byte1byte2` so to compare it with split we need to transform `0.00000000split_byte` to `0.split_byte`.  I suggest adding comment and removing `split2` as it is used only in one place where we can use just `split*256`.

2021-04-12 08:27 UTC, mat-hek commented on lib/boolean_decoder.ex
> +    split2 = split * 256
Having `split_2` is even less meaningful than just replacing it with `split * 256` imho

2021-04-12 08:31 UTC, mat-hek commented on lib/boolean_decoder.ex
> +      Enum.reduce_while(1..@max_int_32, state, fn _i, state ->
If the limitation is artificial, you should either use recursion or an infinite stream, for example `Stream.repeatedly()`. Though recursion may be simpler in this case.

2021-04-12 10:12 UTC, mat-hek requested changes

2021-04-12 10:12 UTC, mat-hek commented on lib/frame_header.ex
> +  defp read_flagged_literals(bool_decoder, amount, literal_size) do
```suggestion
  defp skip_flagged_literals(bool_decoder, amount, literal_size) do
```

2021-04-12 10:12 UTC, mat-hek commented on lib/frame_header.ex
> +    {_v, bool_decoder} = bool_decoder |> BooleanEntropyDecoder.read_literal(3)
`BooleanEntropyDecoder.skip_literal` would be convenient

2021-04-12 10:12 UTC, mat-hek commented on lib/boolean_entropy_decoder.ex
> +  def init_bool_decoder(input) do
```suggestion
  @spec init(binary()) :: {:ok, t()}
  def init(input) do
```

2021-04-14 08:56 UTC, mat-hek approved these changes

2021-04-14 08:56 UTC, merged